### ISSUE TITLE
[Fix] Improve Forms

### ISSUE THREAD

**Issue by Ashuto7h** [Dragsters/Nutrihelp#43]
### Describe the Issue
Currently, the Ux of forms is not good in feel.
Improve the forms and replace their designs with material inputs.

if you have used any package, please add it to the description in your pull request.

**Comment by pratishthaa** [comment]
Do you mean about the patient form? 
I can do changes to the design.
Can I work on it?

**Comment by Ashuto7h** [comment]
Yes please work on. And don't forget to upload screenshots after work.

**Comment by pratishthaa** [comment]
![screenshot](https://user-images.githubusercontent.com/77200165/121819253-b1d50880-cca9-11eb-8a32-0b0e607ccf96.png)
This is what I have worked on so far. 
Can you assign me with the theme issue too so that I can make changes that align for both(this form and in general)?

**Comment by Ashuto7h** [comment]
Yes you can work on themes too

**Comment by pratishthaa** [comment]
I was supposed to be assigned with another issue relating theme..been days since that!
What should I work on then now?

**Comment by Ashuto7h** [comment]
You can work on the new themes issue

**Comment by pratishthaa** [comment]
The issue can b closed now ig?
