### ISSUE TITLE
[Discuss] Suggest Datasets for Heart disease prediction.

### ISSUE THREAD

**Issue by Ashuto7h** [Dragsters/Nutrihelp#44]
This is a Discussion Issue.

The project needs to implement disease predictions for various diseases.
The diabetes prediction is already implemented.
now, the next one is Heart disease prediction.
for that, a good dataset is required. 
suggest your datasets. the final dataset will be selected for further process.

**Comment by Swarnava77** [comment]
Hello @Ashuto7h , kindly assign me this isssue. I am a LGM-Soc 21 participant.

**Comment by Swarnava77** [comment]
The dataset should have columns regarding age, sex, chest pain type, resting blood pressure, serum cholesterol,fasting blood sugar, resting electrocardiographic results, maximum heart rate ,exercise induced angina, oldpeak, the slope of the peak exercise ST segment, number of major vessels, & thal. The main objective refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4. It will help us to find any other trends in heart data to predict certain cardiovascular events or find any clear indications of heart health.
The creators of the  dataset I provided are :
Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
V.A. Medical Center, Long Beach and Cleveland Clinic Foundation: Robert Detrano, M.D., Ph.D.
I have done research regarding collection of best dataset from various sources:
https://www.nature.com/articles/s41597-019-0206-3
https://rstudio-pubs-static.s3.amazonaws.com/396380_639e2f68b09e41a0b05f97b5dc8eb3f2.html
https://archive.ics.uci.edu/ml/datasets/Heart+Disease/
https://towardsdatascience.com/heart-disease-prediction-73468d630cfc
https://www.nature.com/articles/s41598-020-62133-5
https://www.kaggle.com/ronitf/heart-disease-uci
https://www.sciencedirect.com/science/article/pii/S2352914820300125.
Regards
Swarnava

**Comment by Ashuto7h** [comment]
https://www.nature.com/articles/s41598-020-62133-5
https://www.nature.com/articles/s41597-019-0206-3 
These papers do not relate to the dataset you provided.

- The dataset was published in 1988. it is a very old dataset.
- It has only 308 instances. 

Considering the above points there are very less chances that we will continue with this dataset.
If you have a better one, suggest it.

**Comment by Swarnava77** [comment]
Okay
