### ISSUE TITLE
[Feature Request] Tip/Quote of the Day 

### ISSUE THREAD

**Issue by shantamsultania** [Dragsters/Nutrihelp#45]
**Is your feature request related to a problem? Please describe.**

The Idea is to Create a Flask API  with Mongo DB as its Database to provide a random Tip of the day. 

I have not worked on Flutter so I cannot integrate the Whole API of the same so for now, I am just suggesting creating an API and in a matter of let's say 5-10 day when I have a little bit of hands-on flutter I will request a new Issue to integrate it or anyone else can take care of the same but for now, I would like to suggest to make an API to get a tip of the day in the application.

**Comment by Ashuto7h** [comment]
Ok so collect some tips of the day and get started with api.

**Comment by shantamsultania** [comment]
hey @Ashuto7h i think shared the PR for this which is also merged but I was not assigned this issue silly me can you can assign it to me also and then as the PR is already merged we can close this also
