### ISSUE TITLE
 Readme.md update is required 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Dragsters/Nutrihelp#47]
I want to update readme ....please assign this to me

**Comment by Ashuto7h** [comment]
And what changes will you do to readme

**Comment by Ayan-thecodeking** [comment]
> And what changes will you do to readme

want to add contributers section

**Comment by Ashuto7h** [comment]
😃  That issue is preserved for the last moment of SoC.

**Comment by Ayan-thecodeking** [comment]
> 😃 That issue is preserved for the last moment of SoC.

ok @Ashuto7h but do assign me for readme whenever ..u are in the position to update
till then I'll wait 
thanks :)

**Comment by Ayan-thecodeking** [comment]
hey @Ashuto7h  please let me know ...when to update readme 
thanks :)

**Comment by Ashuto7h** [comment]
update now

**Comment by Ayan-thecodeking** [comment]
> update now

Ok thanks @Ashuto7h

**Comment by Ayan-thecodeking** [comment]
Hey @Ashuto7h I hv added contributers and admin section ...pls tell what are the more things I have to add

**Comment by Ashuto7h** [comment]
Thanks. That's enough for now. Just create a PR

**Comment by Ayan-thecodeking** [comment]
> Thanks. That's enough for now. Just create a PR

done @Ashuto7h  review my pr

**Comment by Ayan-thecodeking** [comment]
> > Thanks. That's enough for now. Just create a PR
> 
> done @Ashuto7h review my pr

and please do mention me for any further changes :)
