### ISSUE TITLE
Want to add Code Of Conduct

### ISSUE THREAD

**Issue by Shaishav0507** [Dragsters/Nutrihelp#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hey @mohit-codes @Ashuto7h 
Hey I would like to code of conduct and project admin under Readme file.
Please assign it to me.

**Describe alternatives you've considered**

**Additional context**

**Comment by Ashuto7h** [comment]
Such issues are not welcomed for open source contributions. If you really want to help us, the write some real code.
