### ISSUE TITLE
App Interface Design

### ISSUE THREAD

**Issue by Shivani-Raichandani** [Dragsters/Nutrihelp#5]
## App Interface Design
<details><summary><strong>1. Splash Screen</strong></summary>
</details>

<details><summary><strong>2. Onboarding Screens</strong></summary>

The onboarding Screens contains 4 to 5 illustrations along with some text describing features of app.
</details>

<details><summary><strong>3. Login</strong></summary>

* contains 2 screens. one for entering email. one for OTP.
* Login using email verification only. no need to create password.
</details>

<details><summary><strong>4. Drawer / Sidebar</strong></summary>

* an icon button for dark mode
* __Menu__ 
	* __profile__ - to view all profiles and select a profile.
	* __Reports__ - to view all report history.
	* __Statistics__ - contains all type of data collected by the app, other than reports
	* __Nutri helper__ - to view composition of calories, vitamins, protiens, carbohydrates, Fats, etc in a given food or to view recommendations about a specific nutrient.
	* __About Us / Rate Us__ - to view developer details and give rating or feedback.
</details>

<details>
	<summary><strong>5. Bottom Navigation</strong></summary>

contains 4 navigation buttons for Home, Checkups, Recipies, Articles in same order.

<blockquote>

<details>
	<summary><strong>5.1 Home Screen </strong></summary>

* fitness band status / numbers of steps walked
* button to create diet plan
* button for health checkup recommendations
* Section for tracking daily diet where user can add food item and amount of water he has taken.
* calories burned / Current daily diet plan target and its comparision with today's intakes.
* food item recommendations for today's breakfast, lunch, dinner.
* clicking on every item will navigate you to their detailed views/screens.
</details>

<details>
	<summary><strong>5.2 Checkups Screen</strong></summary>

* button to fill form
* heart disease predictions
* cancer predictions
* diabetes predictions
</details>

<details>
	<summary><strong>5.3 Recipies Screen
	</strong></summary>

Contains Healthy recipies based on user food choices and diet plans(veg, nonveg, recommendations)
</details>

<details>
	<summary><strong>5.4 Articles
	</strong></summary>

Contains health fact of the day, and articles related to health.
</details>

</blockquote>
</details>

**Comment by Ashuto7h** [comment]
Good work Shivani. Others please give your suggestions.
Is there anything that should be added or removed from the given design summary?

**Comment by mohit-codes** [comment]
Great Shivani 
I have gone through the summary it looks good, no significant correction found.
