### ISSUE TITLE
add more badges in README.md file

### ISSUE THREAD

**Issue by Umesh-01** [Dragsters/Nutrihelp#50]
## Describe the Issue
The badges (see the below image) in the README.md file are not sufficient and they are not looking good enough. And one of them also doesn't have a link to the related web page and without that it is of no use.

![image](https://user-images.githubusercontent.com/83420185/121815898-433a7f80-cc96-11eb-9fc2-ada7438c2736.png)

## Suggest the solution
I want to add few more badges with links so that anyone can go to the webpages after clicking on them.
- [ ] will add some more badges like pr, contributors, etc.
- [ ] will add link to the related web pages
- [ ] will align them to the center
- [ ] will make all them of single type

**Comment by Umesh-01** [comment]
sir/mam should I work on this??

**Comment by Ashuto7h** [comment]
They should be colorful and readable. 
Go to it

**Comment by Umesh-01** [comment]
@Ashuto7h sir will you assign some labels for LGMSOC??

**Comment by Umesh-01** [comment]
And sir I also want to inform you that your repo doesn't have code of conduct file...
Should I create a issue for that also??

**Comment by jayant766** [comment]
Assign me plz.
LGM_SOC
