### ISSUE TITLE
Add Let'sGrowMore logo under 'Open Source Program' section

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Dragsters/Nutrihelp#55]
Since this project is part of LGMSOC . I think it's good idea to showcase it in README.md file under Open Source Program section
I will like to work on this issue under LGMSOC if maintainers agree @Ashuto7h

**Comment by Ayan-thecodeking** [comment]
> Since this project is part of LGMSOC . I think it's good idea to showcase it in README.md file under Open Source Program section
> I will like to work on this issue under LGMSOC if maintainers agree @Ashuto7h

thanks for assigning :)

**Comment by Ayan-thecodeking** [comment]
Today I'll make a PR

**Comment by Ayan-thecodeking** [comment]
..

**Comment by jatinjain001** [comment]
I would like to work on it please let me know if it is available
