### ISSUE TITLE
[ML] Create Heart Disease Prediction Model

### ISSUE THREAD

**Issue by Ashuto7h** [Dragsters/Nutrihelp#60]
- Create a new python notebook containing detailed study and analysis of different models for prediction of heart disease risks.
- Use Kaggle / google colab for working on the notebook.
- Use the dataset from https://www.kaggle.com/dileep070/heart-disease-prediction-using-logistic-regression.
- Before working on your notebook, please look at the existing notebook for diabetes prediction. 

Suggestions of all kinds are always welcomed.

**Comment by Akash20x** [comment]
@Ashuto7h 
Please assign me this issue as a part of LGM-SOC'21

**Comment by Akash20x** [comment]
@Ashuto7h Please check my pull request

**Comment by Akash20x** [comment]
@Ashuto7h Please check my pull request
