### ISSUE TITLE
Design Logo for application

### ISSUE THREAD

**Issue by ishitakapoor26** [Dragsters/Nutrihelp#61]
Design Logo for Nutrihelp

**Comment by ishitakapoor26** [comment]
@Ashuto7h pls assign this issue to me.

**Comment by jatinjain001** [comment]
I woould like to work on it , If it is available

**Comment by ishitakapoor26** [comment]
> I woould like to work on it , If it is available

Hey @jatinjain001 I'm already working on it.

**Comment by ishitakapoor26** [comment]
@Ashuto7h pls check these designs...and pls do suggest any color changes if you want!

![Add a subheading](https://user-images.githubusercontent.com/78542333/122913326-eb2b0980-d376-11eb-9202-875783374fcc.png)

**Comment by ishitakapoor26** [comment]
![Add a subheading (1)](https://user-images.githubusercontent.com/78542333/122913462-144b9a00-d377-11eb-9c7e-4e5e59843504.png)

**Comment by ishitakapoor26** [comment]
![Add a subheading (2)](https://user-images.githubusercontent.com/78542333/122913490-1f062f00-d377-11eb-9784-a532de3e700f.png)

**Comment by ishitakapoor26** [comment]
![Add a subheading (3)](https://user-images.githubusercontent.com/78542333/122913511-275e6a00-d377-11eb-9592-56e404b6ee73.png)

**Comment by ishitakapoor26** [comment]
![Add a subheading (4)](https://user-images.githubusercontent.com/78542333/122913588-40671b00-d377-11eb-8ba7-f06d663f7abe.png)

**Comment by Ashuto7h** [comment]
https://github.com/Dragsters/Nutrihelp/issues/61#issuecomment-865884488

This one is good. Just change red to blue and text to blue also.

**Comment by ishitakapoor26** [comment]
> [#61 (comment)](https://github.com/Dragsters/Nutrihelp/issues/61#issuecomment-865884488)
> 
> This one is good. Just change red to blue and text to blue also.

okay

**Comment by ishitakapoor26** [comment]
@Ashuto7h pls check now

![Add a subheading (5)](https://user-images.githubusercontent.com/78542333/122915158-16165d00-d379-11eb-92eb-61732cba4272.png)

**Comment by Ashuto7h** [comment]
Fine now

**Comment by ishitakapoor26** [comment]
@Ashuto7h So may I create a pr?

**Comment by ishitakapoor26** [comment]
@Ashuto7h pls reply may I create a pr if you are satisfied with the design?

**Comment by Ashuto7h** [comment]
Sorry for the delayed response.
Yes you can create the PR

**Comment by ishitakapoor26** [comment]
@Ashuto7h pls review pr.
