### ISSUE TITLE
[Fix] convert the source code of client app to MVVM format

### ISSUE THREAD

**Issue by Ashuto7h** [Dragsters/Nutrihelp#71]
### Describe the Issue
rewrite the whole client lib folder by following the MVVM design pattern.
you can refer to the example given in this repository
https://github.com/flutter-devs/flutter_mvvm_demo/blob/master/lib/view%20models/movie_list_view_model.dart

**Comment by Sahil-kachhap** [comment]
@Ashuto7h I am interested to work on this issue. Do assign me , if it is still open .

**Comment by Ashuto7h** [comment]
Yes it's open. Go for it. 

Just leave a confirmation, so that I can assign it to you

**Comment by Ashuto7h** [comment]
Just leave a confirmation, so that I can assign it to you

**Comment by Sahil-kachhap** [comment]
> Yes it's open. Go for it.
> 
> Just leave a confirmation, so that I can assign it to you

Yes I am ready to work on it

**Comment by ramanjitsingh-hub** [comment]
Can i work on this issue

**Comment by Ashuto7h** [comment]
This project is not actively maintained. @ramanjitsingh-hub
