### ISSUE TITLE
Stroke Prediction

### ISSUE THREAD

**Issue by soma2000-lang** [Dragsters/Nutrihelp#74]
**Is your feature request related to a problem? Please describe.**
Many people die due  to stroke so I would like to build a ml model on it,pmake the predictions and how can it be miniimised

**Describe the solution you'd like**
I would like to bulid  ml model on stroke prediction dataset,do EDA ,predictions  on it

**Comment by soma2000-lang** [comment]
@Ashuto7h 
Please assign me this issue.I am LGMSOC-21 participant

**Comment by Akash20x** [comment]
@soma2000-lang Don't tag me, I am a contributor just like you.

**Comment by Ashuto7h** [comment]
Go for it.
